### ISSUE TITLE
Move legacy templates into settings

### ISSUE THREAD

**Issue by zoglo** [zoglo/contao-legacy-templates#1]
### Feature
* Migrate the current static options into dynamic ones within the maintenance module

### ToDo

* [ ] Create overview within `System > Maintenance`
* [ ] Move elements into Maintenance
* [ ] Implement Save-Callback with Psr6CacheClearer
